- name: Add To GitHub Projects
  uses: actions/add-to-project@v0.0.3
  with:
    # URL of the project to add issues to
    project-url: "https://github.com/diacant/fortesting/projects/1"
    # A GitHub personal access token with write access to the project
    github-token: ${{ secrets.GITHUB_TOKEN }}
    # A comma-separated list of labels to use as a filter for issue to be added
    labeled: "Priority: 1 - Diana" OR "SOC"
    # The behavior of the labels filter, AND to match all labels, OR to match any label (default is OR)
    label-operator: # optional
